# Permalinks
permalink:        pretty

# Setup
title:            fdlane
tagline:          'applies technology to process'
description:      'Christian, Husband, Father, Developer'
url:              http://fdlane.com
baseurl:          /

author:
  name:           'F. DeWayne Lane'
  url:            https://twitter.com/fdlane

destination:       ../blog
paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/fdlane/fdlane.github.io


# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
