# Permalinks
permalink:        pretty

# Setup
title:            FDLane
tagline:          "...applies technology to process"
description:      "Christian, Husband, Father, Developer"
url:              "https://www.fdlane.com"
baseurl:          ""

author:
  name:           'F. DeWayne Lane'
  url:            https://twitter.com/fdlane

paginate_path:   'blog/page:num/' 
paginate:         5

# Custom vars
version:          0.0.1

# Google services
google_analytics: 'UA-90202336-1'

github:
  repo:           https://github.com/fdlane/fdlane.github.io


# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
