# Permalinks
permalink:           pretty

# Setup
title:               fdlane
tagline:             developer
url:                 http://fdlane.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              F. DeWayne Lane
  url:               https://twitter.com/fdlane
  email:             dewayne@fdlane.com

# Custom vars
version:             2.0.0
github:              https://github.com/fdlane
  repo:              https://github.com/fdlane/fdlane.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
