# Permalinks
permalink:        pretty

# Setup
title:            fdlane
tagline:          'developer'
description:      'Christian, husband, father, developer -- Applies technology to process'
url:              http://fdane.com
baseurl:          /

author:
  name:           'F. DeWayne Lane'
  url:            https://twitter.com/fdlane

paginate:         3

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/fdlane/fdlane.github.io

gems:
  - jekyll-paginate
  - jekyll-gist